### ISSUE TITLE
Add babel-plugin-emotion for all enviornments

### ISSUE THREAD

**Issue by DevanB** [ritz078/react-typescript-component-starter-kit#2]
Hey 👋 

I've successfully added babel-plugin-emotion (while using this fantastic boilerplate) to prod and dev environments. 

It's a super helpful plugin that adds the shorthand syntax (`styled('div')` vs `styled.div`) among other goodies.

I've tried adding it to the test environment (because Jest complains when it's ran about the shorthand syntax), but have been unsuccessful. I'm curious if you have added it, and/or would be adding it to this great boilerplate?

Thanks!

**Comment by ritz078** [comment]
I haven't tried that as I prefer avoiding that syntax and just use `css`. I will try.

**Comment by DevanB** [comment]
Thanks for looking into it! I actually migrated away from Emotion due to some other issues, so I should have closed this.

I apologize for that, and will close this now.
